services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: finance-tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Montse1998
    ports:
      - "5432:5432"
